### ISSUE TITLE
Implement Logout Route

### ISSUE THREAD

**Issue by servermonk** [DSC-JSS-NOIDA/foss-events#29]
**Is your feature request related to a problem? Please describe.**
Implement a working logout route

**Describe the solution you'd like**
On going to the logout route, the JWT token should be destroyed and the user would not be able to access protected routes.
The route should be: '/users/logout'. You could make a new file named `logout.js` in the `users` folder and implement logout route there

**Comment by ruddha2001** [comment]
Hello. I would like to take up this issue.

My proposed solution is to use a "blocklist" approach.
I plan to add an `expiresIn` property to the token during the creation. And will have a blocklist maintained in the cache with TTL equal to `expiresIn`. This will mean after a user logout, the JWT will become useless and cannot be used to access any route.

**Comment by OmkarPh** [comment]
That's a great idea @ruddha2001, I was thinking something similar too

If because of some reason, you stop working on it, let me know, otherwise your contribution is appreciated 👍 
Can you explain that "Blocklist" phrase specifically, I didn't get that specifically.

**Comment by ruddha2001** [comment]
Hello @OmkarPh. The concept is really simple.

Destroying JWT makes little sense when we are looking at the server. JWT is just a string which the client(s) use(s) to prove their validity. A valid JWT will stay valid (until it expires).

So some of the popular approaches to handle this are to use Key-Pair value storage or use a Blocklist.

In a blocklist, you maintain a list of JWTs that are debarred from accessing protected routes. Now I am going for a caching approach with TTL so that the blocked JWTs are automatically deleted after a certain time period (otherwise, the list will grow continuously in theory and you can have overflow issues).

You can read more from here https://stackoverflow.com/questions/21978658/invalidating-json-web-tokens

**Comment by OmkarPh** [comment]
Oh I got it, I use a different approach.

I maintain a list of **valid** tokens which is limited to 3 or 5.
Whenever a user signs up or logs in, a new token is added to the valid tokens list. When logout is trigerred, that token is removed from that list,
In short I validate token as well as check if it exists in this list, if it's not in the list, it's considered unauthenticated.

I use this approach, your's is good too, I'd like to see the implementation

**Comment by servermonk** [comment]
hey @ruddha2001, that's a great solution, just to let you know, we have already got the PR on [#19](https://github.com/DSC-JSS-NOIDA/foss-events/issues/19). So you don't need to add expiration time

**Comment by ruddha2001** [comment]
Hello, @servermonk I will not be adding the expiry time but will use the same in my TTL.
If that is fine, can work on this?

**Comment by servermonk** [comment]
sure @ruddha2001, I have assigned this issue to you. All the Best!!
